rules:
  no-undef-secrets:
    secrets:
      - GITHUB_TOKEN
      - FIREBASE_TOKEN_DEV
      - FLUTTERWAVE_SECRET_HASH_DEV
      - FLUTTERWAVE_SECRET_KEY_DEV
      - UPLOAD_BUCKET_NAME_DEV
      - SLACK_WEBHOOK_URL
      - FIREBASE_SERVICE_ACCOUNT_PROD
      - FIREBASE_PROJECT_ID_PROD
      - FLUTTERWAVE_SECRET_HASH_PROD
      - FLUTTERWAVE_SECRET_KEY_PROD
      - UPLOAD_BUCKET_NAME_PROD
